# Steps to enable the this build are:
#
# Generate the OAUTH-TOKEN atd at https://github.com/settings/applications
# Install travis: gem install travis
# Login to travis: travis login
# Encrypt the token: travis encrypt GH_TOKEN=[OAUTH-TOKEN] -r Jasig/cas --add env.global
#

language: java
branches:
  only:
  - master
  - GROUPER_2_1_BRANCH
  - GROUPER_2_2_BRANCH
jdk:
- oraclejdk7
- openjdk6
- openjdk7
- oraclejdk8
before_script:
- cd grouper-parent
script: 
- mvn clean package
before_install:
- chmod -R 777 ./travis/init-travis-build.sh
- ./travis/init-travis-build.sh
after_success:
- mvn clean test cobertura:cobertura coveralls:cobertura

